# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: build
  jobs:
  - job: build
    displayName: build
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      buildParameters.RestoreBuildProjects: '**/*.csproj'
      buildParameters.TestProjects: '**/*UnitTests/*.csproj'

    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: $(buildParameters.RestoreBuildProjects)

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: $(buildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        #publishTestResults: true
        projects: $(buildParameters.TestProjects)
        arguments: --configuration $(BuildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'

    - task: reportgenerator@4
      displayName: Merge code coverage reports
      inputs:
        reports: '**/coverage.cobertura.xml'
        targetdir: $(Build.ArtifactStagingDirectory)/coverlet
        reporttypes: 'Cobertura'
        verbosity: 'Verbose'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish code coverage report'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.ArtifactStagingDirectory)/coverage.cobertura.xml'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        projects: $(buildParameters.RestoreBuildProjects)
        arguments: --configuration $(BuildConfiguration) --output $(build.ArtifactStagingDirectory)
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact
      condition: succeededOrFailed()
      inputs:
        pathtoPublish: $(build.ArtifactStagingDirectory)
        targetPath: 'drop'


- stage: deploy_to_prod
  dependsOn: Build
  condition: and(always(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
    - job: deployToAppService
      displayName: 'DeployToAppService - Prod'
      variables:
      - group: infosafe-variable-group
      steps:
      
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName: 'drop'
          downloadPath: '$(System.DefaultWorkingDirectory)'
      
      - task: FileTransform@1
        inputs:
          folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
          fileType: 'json'
          targetFiles: '**/appsettings.Production.json'
      
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'AzureSC'
          appType: 'webApp'
          appName: 'InfoSafeApi'
          package: '$(System.DefaultWorkingDirectory)/**/*.zip'
          appSettings: '-ASPNETCORE_ENVIRONMENT "Production"'
          deploymentMethod: 'auto'